### ISSUE TITLE
error: failed to download Python-3.6.5.tar.xz using role

### ISSUE THREAD

**Issue by tyler-8** [avanov/ansible-galaxy-pyenv#21]
When I use this role to install a version with
```
pyenv_python_versions:
  - "3.6.5"
```

I am getting the below error:

```
failed: [localhost] (item=3.6.5) => {
    "changed": true,
    "cmd": ". /opt/pyenv/.pyenvrc && pyenv install 3.6.5",
    "delta": "0:02:07.496284",
    "end": "2018-05-23 18:40:00.777833",
    "invocation": {
        "module_args": {
            "_raw_params": ". /opt/pyenv/.pyenvrc && pyenv install 3.6.5",
            "_uses_shell": true,
            "chdir": null,
            "creates": "/opt/pyenv/versions/3.6.5/bin/python",
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "item": "3.6.5",
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2018-05-23 18:37:53.281549",
    "stderr": "Downloading Python-3.6.5.tar.xz...\n-> https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tar.xz\nerror: failed to download Python-3.6.5.tar.xz\n\nBUILD FAILED (CentOS Linux 7 using python-build 1.2.4-2-gdad0fc7)",
    "stderr_lines": [
        "Downloading Python-3.6.5.tar.xz...",
        "-> https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tar.xz",
        "error: failed to download Python-3.6.5.tar.xz",
        "",
        "BUILD FAILED (CentOS Linux 7 using python-build 1.2.4-2-gdad0fc7)"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

If I run `. /opt/pyenv/.pyenvrc && pyenv install 3.6.5` as the `pyenv_owner` it works fine. I'm kind of at a loss of what's causing the issue.

**Comment by avanov** [comment]
Sorry, I still don't understand what causes the issue. What kind of proxy is it?

**Comment by tyler-8** [comment]
It's a corporate proxy, and in order for pyenv's installer (which is using wget or curl) to get through the proxy, it has to be told about it (through the `HTTPS_PROXY` or `HTTP_PROXY` environment variables as an example). Without that proxy definition being provided to pyenv, it can't reach the internet to download the Python version.

I tested it several ways on my machine and found the working solution which I've opened a PR on.

**Comment by avanov** [comment]
Does it mean that other roles fail to download resources from the internet when required?

**Comment by tyler-8** [comment]
It will depend entirely on the role and how it's built, which users it invokes. The main issue here is that your role is doing a `become_user` (which is a good thing depending on use case) inside of the role's tasks, and once that happens any environment variables defined in the top-level playbook outside the role won't be used because they're set for the connection user (which can and likely does differ from the `become_user`).

My PR is non-breaking and just gives the user the option to provide environment variables to the `become_user` if they're needed, otherwise nothing happens.

**Comment by tyler-8** [comment]
I see your point - and you're right that is a better way to handle it. I'll admit ignorance on my part for approaching that initially, but I think I've got it figured out now in my playbook. Thanks @avanov for being helpful and responsive.

**Comment by avanov** [comment]
No worries!
