### ISSUE TITLE
Compilation errors on Ubuntu 18.04 due to missing zlib dependency

### ISSUE THREAD

**Issue by grainednoise** [avanov/ansible-galaxy-pyenv#23]
When this role tries to compile a Python version on Ubuntu (tested it with 3.6.5 ans 2.7.15) it fails because an unmet compile dependency on zlib. After apt installing `zlib1g-dev` the problem went away, so you probably want to include this in the list of Debian dependencies

**Comment by Dutchy-** [comment]
Same on debian stretch

**Comment by avanov** [comment]
Seems like the PR above should fix it. Feel free to reopen it if it's not the case.
