### ISSUE TITLE
pyenv: not found

### ISSUE THREAD

**Issue by musicformellons** [avanov/ansible-galaxy-pyenv#3]
running this:
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  roles:
  - role: avanov.pyenv
     pyenv_path: ~/.pyenv
     pyenv_owner: "MfM"
     pyenv_python_versions:
    - 3.4.3
    - 2.7.9
      pyenv_virtualenvs:
      - venv_name: nodeshot
        py_version: 2.7.9

I get error:

TASK: [avanov.pyenv | Create virtual environments] ***************************\* 
failed: [127.0.0.1] => (item={'py_version': '2.7.9', 'venv_name': 'nodeshot'}) => {"changed": true, "cmd": ". ~/.pyenv/.pyenvrc && pyenv virtualenv 2.7.9 nodeshot", "delta": "0:00:00.001708", "end": "2015-07-01 21:40:46.430191", "item": {"py_version": "2.7.9", "venv_name": "nodeshot"}, "rc": 127, "start": "2015-07-01 21:40:46.428483", "warnings": []}
stderr: /bin/sh: 5: /home/MfM/.pyenv/.pyenvrc: pyenv: not found
/bin/sh: 1: pyenv: not found

FATAL: all hosts have already failed -- aborting

**Comment by avanov** [comment]
Can you try with an absolute path in ``pyenv_path``?

**Comment by musicformellons** [comment]
did that, still error:
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  roles:
     - role: avanov.pyenv
       pyenv_path: user/MfM/.pyenv
       pyenv_owner: "MfM"
       pyenv_python_versions:
         - 3.4.3
         - 2.7.9
       pyenv_virtualenvs:
         - venv_name: nodeshot
           py_version: 2.7.9



TASK: [avanov.pyenv | Create virtual environments] **************************** 
failed: [127.0.0.1] => (item={'py_version': '2.7.9', 'venv_name': 'nodeshot'}) => {"changed": true, "cmd": ". user/MfM/.pyenv/.pyenvrc && pyenv virtualenv 2.7.9 nodeshot", "delta": "0:00:00.998155", "end": "2015-07-02 10:04:19.949125", "item": {"py_version": "2.7.9", "venv_name": "nodeshot"}, "rc": 1, "start": "2015-07-02 10:04:18.950970", "warnings": []}
stderr: pyenv: version `2.7.9' is not installed
/home/MfM/hubiC/ANSIBLE/playbooks/user/MfM/.pyenv/plugins/pyenv-virtualenv/bin/pyenv-virtualenv: line 166: user/MfM/.pyenv/cache/get-pip.py: No such file or directory
pyenv: version `nodeshot' is not installed
error: failed to install pip via get-pip.py
stdout: Downloading/unpacking virtualenv
Installing collected packages: virtualenv
Successfully installed virtualenv
Cleaning up...

FATAL: all hosts have already failed -- aborting
