### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by adborden** [avanov/ansible-galaxy-pyenv#33]
Hello, I'd like to use this role. I find it much easier to manage third-party roles when they are versioned with [semver](https://semver.org/). Would you consider doing that?

**Comment by avanov** [comment]
Is it just a matter of tagging the current master branch or do you want a complete set of supportive documents, like release notes and a changelog? I don't mind having semver tags, it's a good thing to have in general, yet I'd also like to minimise the effort required.

**Comment by adborden** [comment]
Git tags with semver would be plenty sufficient for me, thanks.

**Comment by avanov** [comment]
https://github.com/avanov/ansible-galaxy-pyenv/releases/tag/1.0.0
