### ISSUE TITLE
Valid values for pyenv_env are not obvious

### ISSUE THREAD

**Issue by maxalbert** [avanov/ansible-galaxy-pyenv#36]
Many thanks for providing this ansible-galaxy role @avanov! :)

Just a minor issue for usability: from the README it is not immediately clear what the valid values for the `pyenv_env` are. Looking at `tasks/main.yml` it, the suggested values seem to be `"user"` and `"system"`.

As far as I can tell at a glance, it doesn't actually matter what the value is if it's different from `"user"`, but from a user-friendliness perspective it would be nice if the `"system"` value was documented explicitly because it makes the meaning of the variable clearer.

**Comment by avanov** [comment]
Hi @maxalbert , thank you for your feedback. I agree with you, the documentation is somewhat outdated and I'd like to find some time to clear it up at some point or to accept any changes regarding that as a PR. It's just I barely have spare time for it at the moment and it may take a while.

**Comment by maxalbert** [comment]
No problem @avanov, I totally understand the issue of finding spare time for one's projects.

I opened PR #40 for a quick fix of this particular issue. Feel free to move this information into a different section of the README or document it differently whenever you find time for a more substantial brush-up.
