### ISSUE TITLE
Publish v1.1.0 to Ansible Galaxy

### ISSUE THREAD

**Issue by adborden** [avanov/ansible-galaxy-pyenv#41]
I noticed v1.1.0 was released, thank you! However, when I tried to install it, the version was unavailable in Ansible Galaxy. Would you mind publishing it?

As a work around, I added this to my requirements.yml:
```
- name: avanov.pyenv
  version: 1.1.0
  src: https://github.com/avanov/ansible-galaxy-pyenv.git
```

**Comment by avanov** [comment]
Hi! I think I did it a few months ago, at least, I see the version tag on the dashboard:
<img width="457" alt="Screenshot 2019-08-14 at 10 22 42" src="https://user-images.githubusercontent.com/601955/63010010-800c7400-be7d-11e9-8bc9-8ed11bcaa1f3.png">

I've just re-imported the role on Galaxy, can you try again please?

**Comment by msmyers** [comment]
confirmed available in galaxy

```
install_date: Sun Dec 15 22:34:32 2019
version: 1.1.0
```

**Comment by avanov** [comment]
Closing this, as it looks resolved.
