### ISSUE TITLE
libncursesw5-dev vs libncurses5-dev

### ISSUE THREAD

**Issue by orange888** [avanov/ansible-galaxy-pyenv#44]
Hi,
The pyenv wiki is calling for libncursesw5-dev, you are using libncurses5-dev, are they the same?

https://github.com/pyenv/pyenv/wiki/common-build-problems

Thanks.

**Comment by avanov** [comment]
Hi! The ubuntu package registry says it's a legacy version for supporting wide characters (i.e. those in unicode) - https://packages.ubuntu.com/disco/libncursesw5 I'm not sure if one needs to include them anymore, but if you have a case that requires this library version, I'd like to see it.
