### ISSUE TITLE
pyenv_virtualenvs and pyenv_python_versions should be undefined

### ISSUE THREAD

**Issue by 00willo** [avanov/ansible-galaxy-pyenv#48]
Thanks for developing this role, I've used it a great deal, appreciate your efforts.

I'd like to suggest the following changes to the way the pyenv_virtualenvs are handled.

1. Remove the `pyenv_virtualenvs` and `pyenv_python_versions` from `defaults/main.yml`
1. Add the `when: pyenv_virtualenvs is defined` to the `Create virtual environments` task.
1. Add the `when: pyenv_python_versions is defined` to the `Create virtual environments` task.

This way, if someone wants pyenv installed and no python versions or virtualenvs setup by default at the time this role is applied, then it handles that naturally.  This allows the role to also be used to prepare an environment without requiring guesses to be made as to what the end use may need.

**Comment by avanov** [comment]
the PR with similar proposal has been merged, thank you
