### ISSUE TITLE
allow sudo: true specification

### ISSUE THREAD

**Issue by adamhadani** [avanov/ansible-galaxy-pyenv#5]
Currently tasks have a hard-coded 'sudo: false' clause. This over-rides any user specified 'sudo: true' in a playbook that calls on this role. 
1. Perhaps simply remove these and let the calling playbook decide on usage of sudo?
2. Otherwise perhaps expose as a configurable flag? e.g {{ pyenv_as_sudo }} ?

Could be used for environments where a process manager (e.g supervisord) runs as root and would need to use a pyenv based python / virtualenv ..

**Comment by avanov** [comment]
Isn't it the same as https://github.com/avanov/ansible-galaxy-pyenv/issues/2 ?
I'm not sure if I understand your use case. Could you elaborate on how supervisord is unable to use pyenv installed without sudo?

**Comment by adamhadani** [comment]
@avanov I'm running supervisord as root and would like to install pyenv as root (e.g under /root/.pyenv for example where /root = $HOME for root user)

and yes it seems the same as the closed issue #2 but i don't see a resolution there for how to actually get pyenv to install for the root user?

**Comment by avanov** [comment]
Ok, how about this one.
The role already depends on the ``pyenv_owner`` input. From my perspective, the only case one needs a sudo-wrapped command is when a target virtual environment is to be owned and used by a root user, so the tasks could be modified to indicate that statement accordingly.

I will probably have spare time to try that approach tomorrow, if it sounds reasonable to you.
My goal is to avoid liberal and uncontrollable sudo input, which I hold to be a misuse of the initial idea behind sudo.

**Comment by adamhadani** [comment]
@avanov yep sounds perfectly reasonable and I understand your line of thinking re the promiscuous usage of sudo!

**Comment by avanov** [comment]
Ok, since https://github.com/ansible/ansible/issues/2526 and https://github.com/ansible/ansible/pull/11679 prevent me from evaluating sudo flag with a ``"'$pyenv_owner' == 'root'"`` expression inside a role for the current stable ansible, I have removed the strict ``sudo: no`` directive.

**Comment by avanov** [comment]
I've just re-imported it on Galaxy.

**Comment by adamhadani** [comment]
@avanov - thank you!
